version: '3.8'

networks:
  integration-test-assessment:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      - PORT=:2565
      - DATABASE_URL=postgres://root:root@db/assessment-test-db?sslmode=disable
    volumes:
      - $PWD:/go/src/target
    depends_on:
      - db
    networks: 
      - integration-test-assessment
  db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assessment-test-db
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-assessment